development:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: star_synk_production
  connects_to:
    database:
      writing: cable
  polling_interval: 0.1.seconds
  message_retention: 30.days
